const path = require('pathe');
const FS = require('../lib/fs-wrapper');
const NewPackage = require('../lib/new-package');

test('elm-tooling.json generated by new-package is up to date', async () => {
  // ...or at least equal to the one that this project uses
  const elmToolingJson = await FS.readJsonFile(
    path.resolve(__dirname, '../elm-tooling.json')
  );
  expect(NewPackage.elmToolingJson).toEqual(elmToolingJson);
});
