---
# To get started with Dependabot version updates, you"ll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directories: # Location of package manifests
      - '/'
    schedule:
      interval: 'weekly'
    groups:
      chalk:
        patterns:
          - 'chalk'
          - 'strip-ansi'
          - 'wrap-ansi'
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
      turbo:
        patterns:
          - 'turbo'
          - 'eslint-config-turbo'
          - 'eslint-plugin-turbo'
    ignore:
      - dependency-name: '@typescript-eslint/*'
        update-types:
          - version-update:semver-major
      - dependency-name: 'fs-extra'
        update-types:
          - version-update:semver-major
      - dependency-name: 'chalk'
        update-types:
          - version-update:semver-major
      - dependency-name: 'strip-ansi'
        update-types:
          - version-update:semver-major
      - dependency-name: 'wrap-ansi'
        update-types:
          - version-update:semver-major
  - package-ecosystem: 'github-actions' # See documentation for possible values
    directories: # Location of package manifests
      - '/' # Strangely, this is how to specify "./.github/workflows/*.ya?ml"
      - '/new-package'
    schedule:
      interval: 'weekly'
    groups:
      github-actions:
        patterns:
          - 'actions/*'
  - package-ecosystem: 'elm' # See documentation for possible values
    directories: # Location of package manifests
      - '/ast-codec'
      - '/new-package/review-config-templates/2.3.0'
      - '/parseElm'
      - '/review'
      - '/template'
      - '/test/config-*/'
      - '/test/project-*/'
    schedule:
      interval: 'weekly'
    groups:
      elm:
        patterns:
          - 'elm/*'
      jfmengels/elm-review:
        patterns:
          - 'jfmengels/elm-review'
      jfmengels/elm-review-rules:
        patterns:
          - 'jfmengels/elm-review-*'
      stil4m/elm-syntax:
        patterns:
          - 'stil4m/elm-syntax'
