---
# To get started with Dependabot version updates, you"ll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directories: # Location of package manifests
      - '/'
    schedule:
      interval: 'weekly'
    groups:
      chalk:
        patterns:
          - 'chalk'
          - 'strip-ansi'
          - 'wrap-ansi'
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
      turbo:
        patterns:
          - 'turbo'
          - 'eslint-config-turbo'
          - 'eslint-plugin-turbo'
    ignore:
      # Requires higher engines:
      - dependency-name: '@typescript-eslint/*'
        update-types:
          - version-update:semver-major
      - dependency-name: 'eslint'
        update-types:
          - version-update:semver-major
      - dependency-name: 'eslint-config-xo'
        update-types:
          - version-update:semver-major
      - dependency-name: 'eslint-plugin-n'
        update-types:
          - version-update:semver-major
      - dependency-name: 'eslint-plugin-promise'
        update-types:
          - version-update:semver-major
      - dependency-name: 'eslint-plugin-security'
        update-types:
          - version-update:semver-major
      - dependency-name: 'eslint-plugin-unicorn'
        update-types:
          - version-update:semver-major
      - dependency-name: 'glob'
        update-types:
          - version-update:semver-major
      - dependency-name: 'rimraf'
        update-types:
          - version-update:semver-major
      - dependency-name: 'which'
        update-types:
          - version-update:semver-major

      # ESM-only
      - dependency-name: 'chalk'
        update-types:
          - version-update:semver-major
      - dependency-name: 'find-up'
        update-types:
          - version-update:semver-major
      - dependency-name: 'globby'
        update-types:
          - version-update:semver-major
      - dependency-name: 'got'
        update-types:
          - version-update:semver-major
      - dependency-name: 'ora'
        update-types:
          - version-update:semver-major
      - dependency-name: 'path-key'
        update-types:
          - version-update:semver-major
      - dependency-name: 'strip-ansi'
        update-types:
          - version-update:semver-major
      - dependency-name: 'terminal-link'
        update-types:
          - version-update:semver-major
      - dependency-name: 'wrap-ansi'
        update-types:
          - version-update:semver-major

      # Mostly just need more work.
      - dependency-name: 'chokidar' # See #250.
        update-types:
          - version-update:semver-major
      - dependency-name: 'folder-hash'
        # TODO(lishaduck): Supporting v5 should be trivial, I just need to do it.
        update-types:
          - version-update:semver-major
      - dependency-name: 'fs-extra' # See #120.
        update-types:
          - version-update:semver-major
      - dependency-name: 'prettier' # On #169 (todo list).
        update-types:
          - version-update:semver-major
  - package-ecosystem: 'github-actions' # See documentation for possible values
    directories: # Location of package manifests
      - '/' # Strangely, this is how to specify "./.github/workflows/*.ya?ml"
      - '/new-package'
    schedule:
      interval: 'weekly'
    groups:
      github-actions:
        patterns:
          - 'actions/*'
  - package-ecosystem: 'elm' # See documentation for possible values
    directories: # Location of package manifests
      - '/ast-codec'
      - '/new-package/review-config-templates/2.3.0'
      - '/parseElm'
      - '/review'
      - '/template'
      - '/test/config-*/'
      - '/test/project-*/'
    schedule:
      interval: 'weekly'
    groups:
      elm:
        patterns:
          - 'elm/*'
      jfmengels/elm-review:
        patterns:
          - 'jfmengels/elm-review'
      jfmengels/elm-review-rules:
        patterns:
          - 'jfmengels/elm-review-*'
      stil4m/elm-syntax:
        patterns:
          - 'stil4m/elm-syntax'
